/**
 * Mock data for Phase 2 development.
 * Replace with real Supabase queries in Phase 3.
 */
import type {
  PaymentEvent,
  Bill,
  FamilyRecipient,
  SavingsVault,
  AllocationRule,
  Bucket,
  AiMessage,
} from "@/types/domain";

export const MOCK_USER_ID = "user_mock_001";

// ─── Buckets ─────────────────────────────────────────────────
export const MOCK_BUCKETS: Bucket[] = [
  {
    type: "income",
    label: "Income",
    description: "Global earnings in USDC / EURC",
    balanceInr: 412800,
    balanceNative: 4890,
    nativeCurrency: "USDC",
    stellarAccountOrContractId: null,
  },
  {
    type: "bills",
    label: "Bills",
    description: "Recurring obligations",
    balanceInr: 42000,
    balanceNative: 42000,
    nativeCurrency: "INR",
    stellarAccountOrContractId: null,
  },
  {
    type: "family",
    label: "Family",
    description: "Monthly allowances & remittances",
    balanceInr: 25000,
    balanceNative: 25000,
    nativeCurrency: "INR",
    stellarAccountOrContractId: null,
  },
  {
    type: "savings",
    label: "Savings",
    description: "Yield vault (Soroban)",
    balanceInr: 97680,
    balanceNative: 1158,
    nativeCurrency: "USDC",
    stellarAccountOrContractId: null,
  },
];

// ─── Payment Events ───────────────────────────────────────────
export const MOCK_PAYMENT_EVENTS: PaymentEvent[] = [
  {
    id: "pe_001",
    userId: MOCK_USER_ID,
    direction: "incoming",
    bucket: "income",
    status: "completed",
    amount: 1200,
    currency: "USDC",
    inrEquivalent: 100920,
    fxRate: 84.1,
    fxSpreadPercent: 0.22,
    counterparty: "Acme Corp",
    description: "Invoice #INV-2024-038 — Product Design Sprint",
    rail: "stellar",
    stellarTxHash: null,
    stellarLedger: null,
    sorobanContractId: null,
    settledAt: "2026-07-14T09:12:00Z",
    createdAt: "2026-07-14T09:10:00Z",
  },
  {
    id: "pe_002",
    userId: MOCK_USER_ID,
    direction: "incoming",
    bucket: "income",
    status: "completed",
    amount: 850,
    currency: "USDC",
    inrEquivalent: 71485,
    fxRate: 84.1,
    fxSpreadPercent: 0.18,
    counterparty: "TechStart Inc.",
    description: "Monthly retainer — July 2026",
    rail: "stellar",
    stellarTxHash: null,
    stellarLedger: null,
    sorobanContractId: null,
    settledAt: "2026-07-01T11:45:00Z",
    createdAt: "2026-07-01T11:43:00Z",
  },
  {
    id: "pe_003",
    userId: MOCK_USER_ID,
    direction: "incoming",
    bucket: "income",
    status: "pending",
    amount: 2000,
    currency: "USDC",
    inrEquivalent: null,
    fxRate: null,
    fxSpreadPercent: null,
    counterparty: "GlobalOps Ltd.",
    description: "Invoice #INV-2026-041 — Backend Architecture",
    rail: "stellar",
    stellarTxHash: null,
    stellarLedger: null,
    sorobanContractId: null,
    settledAt: null,
    createdAt: "2026-07-15T07:00:00Z",
  },
  {
    id: "pe_004",
    userId: MOCK_USER_ID,
    direction: "outgoing",
    bucket: "bills",
    status: "completed",
    amount: 18000,
    currency: "INR",
    inrEquivalent: 18000,
    fxRate: 1,
    fxSpreadPercent: 0,
    counterparty: "landlord@upi",
    description: "Rent — July 2026",
    rail: "upi",
    stellarTxHash: null,
    stellarLedger: null,
    sorobanContractId: null,
    settledAt: "2026-07-01T10:00:00Z",
    createdAt: "2026-07-01T09:58:00Z",
  },
  {
    id: "pe_005",
    userId: MOCK_USER_ID,
    direction: "outgoing",
    bucket: "family",
    status: "completed",
    amount: 15000,
    currency: "INR",
    inrEquivalent: 15000,
    fxRate: 1,
    fxSpreadPercent: 0,
    counterparty: "dad@phonepe",
    description: "Monthly allowance — July",
    rail: "upi",
    stellarTxHash: null,
    stellarLedger: null,
    sorobanContractId: null,
    settledAt: "2026-07-01T10:05:00Z",
    createdAt: "2026-07-01T10:03:00Z",
  },
];

// ─── Bills ────────────────────────────────────────────────────
export const MOCK_BILLS: Bill[] = [
  {
    id: "bill_001",
    userId: MOCK_USER_ID,
    name: "Apartment Rent",
    payee: "landlord@ybl",
    payeeType: "upi",
    amount: 18000,
    currency: "INR",
    frequency: "monthly",
    dueDayOfMonth: 1,
    nextDueDate: "2026-08-01",
    isPaused: false,
    isAutopayEnabled: true,
    lastPaidAt: "2026-07-01T10:00:00Z",
    lastPaidAmount: 18000,
    notes: "Whitefield apartment — 2BHK",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "bill_002",
    userId: MOCK_USER_ID,
    name: "Electricity (BESCOM)",
    payee: "bescom@enach",
    payeeType: "bank_account",
    amount: 2400,
    currency: "INR",
    frequency: "monthly",
    dueDayOfMonth: 15,
    nextDueDate: "2026-07-15",
    isPaused: false,
    isAutopayEnabled: true,
    lastPaidAt: "2026-06-15T08:00:00Z",
    lastPaidAmount: 2180,
    notes: null,
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "bill_003",
    userId: MOCK_USER_ID,
    name: "Netflix",
    payee: "netflix@icici",
    payeeType: "upi",
    amount: 649,
    currency: "INR",
    frequency: "monthly",
    dueDayOfMonth: 10,
    nextDueDate: "2026-08-10",
    isPaused: false,
    isAutopayEnabled: true,
    lastPaidAt: "2026-07-10T00:00:00Z",
    lastPaidAmount: 649,
    notes: null,
    createdAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "bill_004",
    userId: MOCK_USER_ID,
    name: "Home Loan EMI",
    payee: "hdfcbank@upi",
    payeeType: "upi",
    amount: 22000,
    currency: "INR",
    frequency: "monthly",
    dueDayOfMonth: 5,
    nextDueDate: "2026-08-05",
    isPaused: false,
    isAutopayEnabled: false,
    lastPaidAt: "2026-07-05T09:00:00Z",
    lastPaidAmount: 22000,
    notes: "HDFC HL-2341 — parents' home",
    createdAt: "2024-06-01T00:00:00Z",
  },
];

// ─── Family Recipients ────────────────────────────────────────
export const MOCK_FAMILY: FamilyRecipient[] = [
  {
    id: "fam_001",
    userId: MOCK_USER_ID,
    name: "Dad",
    relationship: "Parent",
    avatarInitials: "D",
    payeeType: "upi",
    payeeIdentifier: "dad@phonepe",
    payeeLabel: "PhonePe",
    monthlyAllowance: 10000,
    allowanceEnabled: true,
    lastTransferAmount: 10000,
    lastTransferAt: "2026-07-01T10:05:00Z",
    totalTransferredInr: 120000,
    notes: "Monthly pocket money",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "fam_002",
    userId: MOCK_USER_ID,
    name: "Mom",
    relationship: "Parent",
    avatarInitials: "M",
    payeeType: "upi",
    payeeIdentifier: "mom@paytm",
    payeeLabel: "Paytm",
    monthlyAllowance: 5000,
    allowanceEnabled: true,
    lastTransferAmount: 5000,
    lastTransferAt: "2026-07-01T10:06:00Z",
    totalTransferredInr: 60000,
    notes: "Grocery & household",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "fam_003",
    userId: MOCK_USER_ID,
    name: "Sister",
    relationship: "Sibling",
    avatarInitials: "S",
    payeeType: "upi",
    payeeIdentifier: "sis@gpay",
    payeeLabel: "Google Pay",
    monthlyAllowance: null,
    allowanceEnabled: false,
    lastTransferAmount: 8000,
    lastTransferAt: "2026-06-15T14:00:00Z",
    totalTransferredInr: 30000,
    notes: "College fees & misc",
    createdAt: "2026-02-01T00:00:00Z",
  },
];

// ─── Savings Vault ────────────────────────────────────────────
export const MOCK_VAULT: SavingsVault = {
  id: "vault_001",
  userId: MOCK_USER_ID,
  principalUsdc: 1100,
  totalValueUsdc: 1158.4,
  yieldEarnedUsdc: 58.4,
  estimatedApyPercent: 5.8,
  sorobanContractId: null,
  vaultSharesHeld: null,
  autoDepositThresholdInr: 50000,
  autoDepositEnabled: true,
  lastYieldClaimedAt: null,
  updatedAt: "2026-07-14T00:00:00Z",
};

// ─── Allocation Rules ─────────────────────────────────────────
export const MOCK_RULES: AllocationRule[] = [
  {
    id: "rule_001",
    userId: MOCK_USER_ID,
    name: "Default Allocation",
    incomeSourceFilter: null,
    allocations: [
      { bucket: "bills", percent: 40 },
      { bucket: "family", percent: 15 },
      { bucket: "savings", percent: 20 },
      { bucket: "income", percent: 25 },
    ],
    isActive: true,
    aiGenerated: false,
    aiPrompt: null,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
  },
];

// ─── AI Messages ──────────────────────────────────────────────
export const MOCK_AI_MESSAGES: AiMessage[] = [
  {
    id: "msg_001",
    role: "assistant",
    content:
      "Hi! I'm your DeliteX AI assistant. I can help you set up allocation rules, manage your bills, and optimize your finances. Try saying something like \"Always pay rent first\" or \"Allocate 10% to my parents every month\".",
    parsedRule: null,
    llmModel: null,
    llmLatencyMs: null,
    createdAt: new Date().toISOString(),
  },
];
